### ISSUE TITLE
Import fails: from Products.PloneFormGen import implementedOrProvidedBy

### ISSUE THREAD

**Issue by acsr** [collective/collective.pfgpreview#2]
The line::

    from Products.PloneFormGen import implementedOrProvidedBy

at https://github.com/collective/collective.pfgpreview/blob/master/collective/pfgpreview/preview.py#L3

drops an error for me::

    ImportError: cannot import name implementedOrProvidedBy

When I google I cannot find any "implementedOrProvidedBy" module or hint how to fix the import

-- Armin

    Traceback (most recent call last):
      File "/home/user/instances/mybuildout-dev/parts/instance/bin/interpreter", line 276, in <module>
        exec(compile(__file__f.read(), __file__, "exec"))
      File "/home/user/instances/mybuildout-dev/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/run.py", line 76, in <module>
        run()
      File "/home/user/instances/mybuildout-dev/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/run.py", line 22, in run
        starter.prepare()
      File "/home/user/instances/mybuildout-dev/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/__init__.py", line 86, in prepare
        self.startZope()
      File "/home/user/instances/mybuildout-dev/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/__init__.py", line 262, in startZope
        Zope2.startup()
      File "/home/user/instances/mybuildout-dev/eggs/Zope2-2.13.22-py2.7.egg/Zope2/__init__.py", line 47, in startup
        _startup()
      File "/home/user/instances/mybuildout-dev/eggs/Zope2-2.13.22-py2.7.egg/Zope2/App/startup.py", line 118, in startup
        load_zcml()
      File "/home/user/instances/mybuildout-dev/eggs/Zope2-2.13.22-py2.7.egg/Zope2/App/startup.py", line 52, in load_zcml
        load_site()
      File "/home/user/instances/mybuildout-dev/eggs/Zope2-2.13.22-py2.7.egg/Zope2/App/zcml.py", line 46, in load_site
        _context = xmlconfig.file(site_zcml)
      File "/home/user/instances/mybuildout-dev/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 649, in file
        include(context, name, package)
      File "/home/user/instances/mybuildout-dev/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
        processxmlfile(f, context)
      File "/home/user/instances/mybuildout-dev/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
        parser.parse(src)
      File "/home/user/instances/Python-2.7/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
        xmlreader.IncrementalParser.parse(self, source)
      File "/home/user/instances/Python-2.7/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
        self.feed(buffer)
      File "/home/user/instances/Python-2.7/lib/python2.7/xml/sax/expatreader.py", line 210, in feed
        self._parser.Parse(data, isFinal)
      File "/home/user/instances/Python-2.7/lib/python2.7/xml/sax/expatreader.py", line 352, in end_element_ns
        self._cont_handler.endElementNS(pair, None)
      File "/home/user/instances/mybuildout-dev/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
        self.context.end()
      File "/home/user/instances/mybuildout-dev/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
        self.stack.pop().finish()
      File "/home/user/instances/mybuildout-dev/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 706, in finish
        actions = self.handler(context, **args)
      File "/home/user/instances/mybuildout-dev/eggs/Zope2-2.13.22-py2.7.egg/OFS/metaconfigure.py", line 46, in loadProducts
        xmlconfig.include(_context, zcml, package=product)
      File "/home/user/instances/mybuildout-dev/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
        processxmlfile(f, context)
      File "/home/user/instances/mybuildout-dev/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
        parser.parse(src)
      File "/home/user/instances/Python-2.7/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
        xmlreader.IncrementalParser.parse(self, source)
      File "/home/user/instances/Python-2.7/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
        self.feed(buffer)
      File "/home/user/instances/Python-2.7/lib/python2.7/xml/sax/expatreader.py", line 210, in feed
        self._parser.Parse(data, isFinal)
      File "/home/user/instances/Python-2.7/lib/python2.7/xml/sax/expatreader.py", line 352, in end_element_ns
        self._cont_handler.endElementNS(pair, None)
      File "/home/user/instances/mybuildout-dev/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
        self.context.end()
      File "/home/user/instances/mybuildout-dev/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
        self.stack.pop().finish()
      File "/home/user/instances/mybuildout-dev/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 706, in finish
        actions = self.handler(context, **args)
      File "/home/user/instances/mybuildout-dev/eggs/z3c.autoinclude-0.3.5-py2.7.egg/z3c/autoinclude/zcml.py", line 104, in includePluginsDirective
        includeZCMLGroup(_context, info, filename)
      File "/home/user/instances/mybuildout-dev/eggs/z3c.autoinclude-0.3.5-py2.7.egg/z3c/autoinclude/zcml.py", line 30, in includeZCMLGroup
        include(_context, filename, includable_package)
      File "/home/user/instances/mybuildout-dev/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
        processxmlfile(f, context)
      File "/home/user/instances/mybuildout-dev/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
        parser.parse(src)
      File "/home/user/instances/Python-2.7/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
        xmlreader.IncrementalParser.parse(self, source)
      File "/home/user/instances/Python-2.7/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
        self.feed(buffer)
      File "/home/user/instances/Python-2.7/lib/python2.7/xml/sax/expatreader.py", line 210, in feed
        self._parser.Parse(data, isFinal)
      File "/home/user/instances/Python-2.7/lib/python2.7/xml/sax/expatreader.py", line 352, in end_element_ns
        self._cont_handler.endElementNS(pair, None)
      File "/home/user/instances/mybuildout-dev/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
        self.context.end()
      File "/home/user/instances/mybuildout-dev/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
        self.stack.pop().finish()
      File "/home/user/instances/mybuildout-dev/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 705, in finish
        args = toargs(context, *self.argdata)
      File "/home/user/instances/mybuildout-dev/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 1397, in toargs
        args[str(name)] = field.fromUnicode(s)
      File "/home/user/instances/mybuildout-dev/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/fields.py", line 137, in fromUnicode
        value = self.context.resolve(name)
      File "/home/user/instances/mybuildout-dev/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 179, in resolve
        mod = __import__(mname, *_import_chickens)
      File "/home/user/instances/mybuildout-dev/src/collective.pfgpreview/collective/pfgpreview/preview.py", line 3, in <module>
        from Products.PloneFormGen import implementedOrProvidedBy
    zope.configuration.xmlconfig.ZopeXMLConfigurationError: File "/home/user/instances/mybuildout-dev/parts/instance/etc/site.zcml", line 16.2-16.23
        ZopeXMLConfigurationError: File "/home/user/instances/mybuildout-dev/eggs/Products.CMFPlone-4.3.3-py2.7.egg/Products/CMFPlone/configure.zcml", line 98.4-102.10
        ZopeXMLConfigurationError: File "/home/user/instances/mybuildout-dev/src/collective.pfgpreview/collective/pfgpreview/configure.zcml", line 7.4-13.10
        ImportError: cannot import name implementedOrProvidedBy

**Comment by sunew** [comment]
fixed in pullrequest by acsr.
